import sys
print("-----------------------------------------")
print("---------------------------")
print("---------------")
print("--")
print(sys.version)
print(sys.version_info)
print(sys.executable)
print("--") 
print("---------------")
print("---------------------------")
print("-----------------------------------------")
